apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-dashboard
  labels:
    name: monitoring-dashboard
    app.kubernetes.io/name: monitoring-dashboard
    app.kubernetes.io/component: namespace
