apiVersion: v1
kind: Service
metadata:
  name: monitoring-dashboard
  namespace: monitoring-dashboard
  labels:
    app.kubernetes.io/name: monitoring-dashboard
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: monitoring-dashboard
    app.kubernetes.io/component: application
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
